# https://www.mkdocs.org/user-guide/configuration/
site_name: pyreversi
site_description: Python reversi
repo_name: pyreversi
repo_url: https://github.com/kkinugasa/pyreversi

strict: true

dev_addr: 127.0.0.1:8888
docs_dir: docs
site_dir: site

nav:
  - Home: index.md

theme:
  name: "material"
plugins:
  - search
  # https://mkdocstrings.github.io/python/usage/
  - mkdocstrings:
      watch:
        - pyreversi
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_root_members_full_path: true
            show_category_heading: false
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: false
            line_length: 88
            merge_init_into_class: true
            show_source: true
            show_bases: true
            show_submodules: true
            group_by_category: true
            heading_level: 2
            members_order: alphabetical
            docstring_section_style: spacy
