;; mypy does not support pyproject.toml yet
;; https://github.com/python/mypy/issues/5205
[mypy]
;; https://mypy.readthedocs.io/en/stable/config_file.html
namespace_packages = True

;; Disallow dynamic typing
disallow_any_unimported = False
; disallow_any_expr = True
; disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_generics = True
disallow_subclassing_any = True

;; Untyped definitions and calls
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True

;; None and Optional handlng
no_implicit_optional = True
strict_optional = True

;; Configuring warnings
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_return_any = True
warn_unreachable = True

;;Suppressing errors
show_none_errors = True
ignore_errors = False

;; Miscellaneous strictness flags
allow_untyped_globals = False
allow_redefinition = False
; implicit_reexport = False
strict_equality = True

;; Configuring error messages
; show_error_context = True
show_column_numbers = True
show_error_codes = True
pretty = True
color_output = True
error_summary = True
; show_absolute_path = True

;; Miscellaneous
warn_unused_configs = True

; [mypy-numpy.*]
; ignore_missing_imports=True

; https://numpy.org/doc/stable/reference/typing.html
plugins = numpy.typing.mypy_plugin
